# Generated by Django 4.2.2 on 2023-06-07 21:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimeChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('season', models.IntegerField(null=True)),
                ('source', models.URLField(null=True)),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='NMA_Worlds.anime')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.URLField(null=True)),
                ('image', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='mangas', to='NMA_Worlds.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('book', models.IntegerField(null=True)),
                ('source', models.URLField(null=True)),
                ('anime_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NMA_Worlds.animechapter')),
                ('images', models.ManyToManyField(blank=True, to='NMA_Worlds.image')),
                ('manga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='NMA_Worlds.manga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='novels', to='NMA_Worlds.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('other_names', models.TextField(null=True)),
                ('anime', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='NMA_Worlds.anime')),
                ('genres', models.ManyToManyField(blank=True, related_name='series', to='NMA_Worlds.genre')),
                ('manga', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='NMA_Worlds.manga')),
                ('novel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='NMA_Worlds.novel')),
                ('tags', models.ManyToManyField(blank=True, related_name='series', to='NMA_Worlds.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('season', models.IntegerField(null=True)),
                ('source', models.URLField(null=True)),
                ('anime_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NMA_Worlds.animechapter')),
                ('images', models.ManyToManyField(blank=True, to='NMA_Worlds.image')),
                ('manga_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NMA_Worlds.mangachapter')),
                ('novel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='NMA_Worlds.novel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NMA_Worlds.status'),
        ),
        migrations.AddField(
            model_name='mangachapter',
            name='novel_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NMA_Worlds.novelchapter'),
        ),
        migrations.AddField(
            model_name='manga',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NMA_Worlds.status'),
        ),
        migrations.AddField(
            model_name='animechapter',
            name='manga_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NMA_Worlds.mangachapter'),
        ),
        migrations.AddField(
            model_name='animechapter',
            name='novel_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NMA_Worlds.novelchapter'),
        ),
        migrations.AddField(
            model_name='animechapter',
            name='videos',
            field=models.ManyToManyField(blank=True, to='NMA_Worlds.video'),
        ),
        migrations.AddField(
            model_name='anime',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='animes', to='NMA_Worlds.author'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NMA_Worlds.status'),
        ),
    ]
