version: "3.9"

services:

  web:
    image: horou/nma-web:1.0
    container_name: NMA_WEB
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./web/certs:/certificates:ro
    depends_on:
      - api
    networks:
      - proxy

  api:
    image: horou/nma-api:1.0
    container_name: NMA_API
    build: ./api
    env_file:
      - .env
    environment:
      DB_URL: ${DB_TYPE}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTION}
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.fastapi.tls=true
      - traefik.http.routers.fastapi.tls.certresolver=letsencrypt
      - traefik.http.services.fastapi.loadbalancer.server.port=${API_PORT}
    volumes:
      - ../files:${FILES_PATH}
    depends_on:
      - db
    networks:
      - proxy

  db:
    image: horou/nma-db:1.0
    container_name: NMA_DB
    build: ./db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - proxy

volumes:
  db_data:

networks:
  proxy:
